// Generates lib/l10n/lookup.g.dart: a key → string lookup over the ARB
// strings without placeholders, so content JSON can name strings by key.
//
//   dart run tool/gen_lookup.dart
import 'dart:convert';
import 'dart:io';

const arbPath = 'lib/l10n/app_en.arb';
const outPath = 'lib/l10n/lookup.g.dart';

String generate(Map<String, dynamic> arb) {
  final keys = [
    for (final e in arb.entries)
      if (!e.key.startsWith('@') && !(e.value as String).contains('{')) e.key,
  ]..sort();
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_lookup.dart from $arbPath. Do not edit.')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln()
    ..writeln("import 'app_localizations.dart';")
    ..writeln()
    ..writeln('/// Every ARB key without placeholders.')
    ..writeln('const arbKeys = <String>{')
    ..writeAll([for (final k in keys) "  '$k',\n"])
    ..writeln('};')
    ..writeln()
    ..writeln('/// The string for [key] in [l], or null if there is no such key.')
    ..writeln('String? lookupArb(AppLocalizations l, String key) => switch (key) {')
    ..writeAll([for (final k in keys) "  '$k' => l.$k,\n"])
    ..writeln('  _ => null,')
    ..writeln('};');
  return b.toString();
}

void main() {
  final arb = jsonDecode(File(arbPath).readAsStringSync()) as Map<String, dynamic>;
  File(outPath).writeAsStringSync(generate(arb));
  stdout.writeln('Wrote $outPath');
}
