// Writes ../docs/RECORDING_SCRIPT.md: every narration line to record, in
// English and Albanian, with whether the file exists yet.
//
//   dart run tool/gen_recording_script.dart
import 'dart:convert';
import 'dart:io';

/// ARB keys that are only read by grown-ups, never narrated.
const parentOnlyPrefixes = ['gate', 'debug', 'parent', 'language', 'privacy', 'purchase', 'appTitle'];

Map<String, dynamic> _arb(String l) => jsonDecode(File('lib/l10n/app_$l.arb').readAsStringSync()) as Map<String, dynamic>;

/// Narration files are named by ARB key (see lib/core/keys.dart); animal sounds by the
/// camelCase form of their `sfx.` key.
void main() {
  final en = _arb('en');
  final sq = _arb('sq');
  final keys = [
    for (final k in en.keys)
      if (!k.startsWith('@') && !parentOnlyPrefixes.any(k.startsWith)) k,
  ];
  final sounds = <String>{};
  for (final f in Directory('assets/content/vocab').listSync().whereType<File>()) {
    final items = (jsonDecode(f.readAsStringSync()) as Map<String, dynamic>)['items'] as List<dynamic>;
    for (final i in items.cast<Map<String, dynamic>>()) {
      if (i['soundKey'] case final String s) sounds.add(s);
    }
  }
  bool has(String path) => File('assets/$path').existsSync();
  final b = StringBuffer()
    ..writeln('# Recording script')
    ..writeln()
    ..writeln('Generated by `app/tool/gen_recording_script.dart`. Do not edit by hand.')
    ..writeln()
    ..writeln('Record each line as `app/assets/audio/{en,sq}/<key>.ogg` (standard Albanian, native speakers;')
    ..writeln('warm, slow, smiling). Lines with `{…}` placeholders are recorded per value, e.g.')
    ..writeln('`levelNumber` → `levelNumber_1.ogg` … (see the game that uses them).')
    ..writeln()
    ..writeln('| Key | English | Shqip | en | sq |')
    ..writeln('| --- | --- | --- | --- | --- |');
  var done = 0;
  for (final k in keys) {
    final e = has('audio/en/$k.ogg');
    final s = has('audio/sq/$k.ogg');
    if (e && s) done++;
    String cell(Object? v) => '$v'.replaceAll('|', '\\|').replaceAll('\n', ' ');
    b.writeln('| `$k` | ${cell(en[k])} | ${cell(sq[k])} | ${e ? '✔' : '—'} | ${s ? '✔' : '—'} |');
  }
  b
    ..writeln()
    ..writeln('## Animal sounds (language-independent)')
    ..writeln()
    ..writeln('Record as `app/assets/audio/sfx/<name>.ogg`.')
    ..writeln()
    ..writeln('| File | Recorded |')
    ..writeln('| --- | --- |');
  for (final s in sounds.toList()..sort()) {
    final path = 'audio/sfx/${_camel(s.substring(4))}.ogg';
    b.writeln('| `$path` | ${has(path) ? '✔' : '—'} |');
  }
  b
    ..writeln()
    ..writeln('**Progress:** $done of ${keys.length} lines recorded in both languages; '
        '${sounds.where((s) => has('audio/sfx/${_camel(s.substring(4))}.ogg')).length} of ${sounds.length} animal sounds.');
  File('../docs/RECORDING_SCRIPT.md').writeAsStringSync(b.toString());
  stdout.writeln('Wrote docs/RECORDING_SCRIPT.md (${keys.length} lines)');
}

String _camel(String key) {
  final parts = key.split(RegExp(r'[._]')).where((p) => p.isNotEmpty).toList();
  return [parts.first, for (final p in parts.skip(1)) p[0].toUpperCase() + p.substring(1)].join();
}
